import './globals.css';
import { Rubik } from 'next/font/google';

//component imports
import NavBar from './components/NavBar/NavBar';

const rubik = Rubik({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={rubik.className}>
        <NavBar />
        {children}
      </body>
    </html>
  );
}
